version: '3'
services:
  client:
    build: ./client
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - ./client/.env

  server:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./server/firebase-admin-key.json:/app/firebase-admin-key.json
    environment:
      - NODE_ENV=development
    env_file:
      - ./server/.env

volumes:
  firebase_admin_key: